# GitHub Pages 部署工作流

name: Deploy to GitHub Pages

on:
  # 在推送到main分支时触发部署
  push:
    branches: [ main ]
  # 允许从Actions标签手动触发工作流
  workflow_dispatch:

# 设置工作流权限，允许部署GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: main
      
      # 设置GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      # 复制文件到发布目录
      - name: Prepare files for deployment
        run: |
          mkdir -p public
          # 复制HTML文件
          cp -r "创建计算器的视觉界面和静态交互/"/* public/
          # 复制JavaScript文件
          mkdir -p public/js
          cp -r "现计算器最核心的运算和状态管理/"/*.js public/js/
          # 更新script标签路径
          sed -i 's|../现计算器最核心的运算和状态管理/features.js|js/features.js|g' public/index.html
          sed -i 's|../现计算器最核心的运算和状态管理/history.js|js/history.js|g' public/index.html
      
      # 构建静态网站
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./public
          destination: ./_site
      
      # 部署到GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2